import { describe, expect, it } from "vitest";

import enUS from "../../locales/en-US.json";
// The Rust test owns + regenerates this golden (src-tauri/tests/
// error_variant_kinds.rs). Imported statically (not via node:fs) because src/
// is type-checked by tsc, which has no @types/node in scope -- mirroring the
// static JSON import already used by i18n-catalogs.test.ts.
import snapshot from "../../../src-tauri/tests/error_variant_kinds.json";

// Cross-boundary alignment guard (issue #128). The Rust core exports the wire
// `kind` set of every typed IPC error enum to a committed golden generated by
// src-tauri/tests/error_variant_kinds.rs (the compiler truth -- no parse drift);
// this test asserts that golden's variant set matches the frontend's catalog-id
// contract below, and that every catalog id the contract names exists in en-US.
//
// Three complementary i18n guards:
//   - scripts/check-i18n.mjs         frontend-internal: source extract == en == zh.
//   - i18n-catalogs.test.ts          en-US == zh-CN key sets (fast in-process).
//   - THIS test                      cross-boundary: Rust variant set == catalog ids.
// check-i18n.mjs pins en-US == extract, so an id present in en-US here is
// transitively in the formatjs extract -- no need to spawn @formatjs/cli again
// (that source-coverage half is check-i18n.mjs's job, not this test's).
//
// Adding a Rust variant: (1) cargo regenerates the golden (the Rust test forces
// a construction line), (2) this test's contract map must gain the new kind with
// its catalog id, (3) the catalog + the format* switch in api.ts gain the id /
// case (the TS `never` guard catches a missing case). The cascade is the point
// -- a backend variant can no longer ship without its frontend catalog id.

// The cross-boundary contract: for each (enum, kind) the catalog id the frontend
// renders it through (see the format* switches in api.ts), or null when the
// variant delegates to a sub-enum and carries no direct message (e.g.
// SessionError::Resume recurses into ResumeError). This map is hand-maintained
// against those switches; the @formatjs/cli extract constraint (an id MUST be
// a literal at each intl.formatMessage call site) forbids centralizing the ids
// in a shared map the formatters consume, so the duplication is structural --
// it exists to be cross-checked against Rust here. NOTE: this test guards the
// map <-> Rust and map <-> en-US legs only; the map <-> api.ts-switch leg is
// maintained by hand and backstopped indirectly -- a switch's id is also a
// formatjs extract, so check-i18n.mjs (extract == en-US) flags a catalog id the
// switch stops using, and the TS `never` guard flags a missing case once
// the mirroring TS type adds the variant.
const CATALOG_IDS: Readonly<Record<string, Readonly<Record<string, string | null>>>> = {
  TurnFailure: {
    Execute: "error.turn.execute",
    Resource: "error.turn.resource",
    NotWired: "error.turn.notWired",
    InvalidConfig: "error.turn.invalidConfig",
    StaleReference: "error.turn.stale",
  },
  SessionError: {
    InvalidId: "error.session.invalidId",
    NotFound: "error.session.notFound",
    Resuming: "error.session.resuming",
    InFlight: "error.session.inFlight",
    Resume: null, // recurses ResumeError
    RemoveSource: null, // recurses RemoveSourceError
    RenameDataset: null, // recurses RenameError
    RenameSession: "error.session.renameEmpty",
    Turn: null, // recurses TurnError
    Engine: "error.session.engine",
  },
  RemoveSourceError: {
    NotFound: "error.dataset.notFound",
    IsActive: "error.dataset.removeActive",
    NotActive: "error.dataset.notActive",
    InvalidContinueWith: "error.dataset.invalidContinueWith",
  },
  RenameError: {
    NotFound: "error.dataset.notFound",
    DisplayTaken: "error.dataset.displayTaken",
    InvalidLabel: "error.dataset.invalidLabel",
  },
  TurnError: {
    UnknownDataset: "error.dataset.notFound",
    Execute: "error.turn.execute",
  },
  ResumeError: {
    Load: null, // recurses DuckLoadError
    SourceMissing: "error.resume.sourceMissing",
    Replay: "error.resume.replay",
    ActiveMissing: "error.resume.activeMissing",
    Cancelled: "error.resume.cancelled",
    Aborted: "error.resume.aborted",
    AlreadyOpen: "error.duck.alreadyOpen",
  },
  DuckLoadError: {
    Io: "error.duck.loadIo",
    Parse: "error.duck.loadParse",
    VersionMismatch: "error.duck.versionMismatch",
    Migration: "error.duck.migration",
  },
  SaveError: {
    Serialize: "error.save.serialize",
    Io: "error.save.io",
    Rename: "error.save.rename",
    AlreadyOpen: "error.duck.alreadyOpen",
  },
  StoreCommandError: {
    OpenConflict: "error.store.openConflict",
    BlankName: "error.session.renameEmpty", // reuses rename_session's id
    IoFailure: "error.store.ioFailure",
    KeychainFailure: "error.store.keychainFailure",
    ConfigWriteFailure: "error.store.configWriteFailure",
  },
  SkillError: {
    InvalidName: "error.skill.invalidName",
    InvalidSkill: "error.skill.invalidSkill",
    NoSuchSkill: "error.skill.notFound",
    NameTaken: "error.skill.nameTaken",
    ReadOnly: "error.skill.readOnly",
    FsFailure: "error.skill.fsFailure",
  },
  RenameSessionError: {
    EmptyName: "error.session.renameEmpty",
  },
  MigrationError: {
    // Both variants ride the parent DuckLoadError::Migration message; their data
    // only feeds the technical-details fold, so they have no own catalog id.
    NoTransform: null,
    Field: null,
  },
};

describe("cross-boundary error variant <-> i18n catalog (issue #128)", () => {
  it("covers exactly the enums the Rust snapshot exports", () => {
    // A new error enum on the Rust side (or a dropped one) must be acknowledged
    // here -- the snapshot is the compiler truth, the contract map is the
    // frontend's matching half.
    expect(Object.keys(CATALOG_IDS).sort()).toEqual(Object.keys(snapshot).sort());
  });

  it("each enum's contract kinds equal the Rust snapshot kinds", () => {
    // Catches a Rust variant added/removed/renamed without updating the
    // contract map (and thus without a catalog id / format* case).
    for (const [enumName, kinds] of Object.entries(snapshot)) {
      const contractKinds = Object.keys(CATALOG_IDS[enumName]).sort();
      expect(contractKinds, `${enumName} kinds`).toEqual([...kinds].sort());
    }
  });

  it("every non-null catalog id exists in en-US.json", () => {
    // Catches a contract id that names no catalog entry. en-US membership
    // transitively implies formatjs-extract membership (check-i18n.mjs pins
    // en-US == extract) and zh-CN membership (i18n-catalogs.test.ts pins en==zh).
    const enKeys = new Set(Object.keys(enUS));
    for (const [enumName, byKind] of Object.entries(CATALOG_IDS)) {
      for (const [kind, id] of Object.entries(byKind)) {
        if (id !== null) {
          expect(
            enKeys.has(id),
            `${enumName}::${kind} -> "${id}" missing from en-US.json`,
          ).toBe(true);
        }
      }
    }
  });
});
